addSbtPlugin("org.scalameta" 	%  "sbt-scalafmt" 	    % "2.4.2")
addSbtPlugin("com.timushev.sbt" %  "sbt-updates"            % "0.5.2")
addSbtPlugin("io.spray"         %  "sbt-revolver"           % "0.9.1")
addSbtPlugin("org.scalastyle"   %% "scalastyle-sbt-plugin"  % "1.0.0")
addSbtPlugin("org.scoverage"    %  "sbt-scoverage"          % "1.6.1")
addSbtPlugin("org.wartremover"  %  "sbt-wartremover"        % "2.4.13")
